// All 151 facts sourced and paraphrased from BBC Science Focus (sciencefocus.com/science/fun-facts)
const FACTS = [
  { id: 1, text: "A typical cloud weighs around one million tonnes — it just floats because it's slightly less dense than the surrounding air.", source: "BBC Science Focus" },
  { id: 2, text: "Identical twins don't share fingerprints. Random conditions in the womb shape each twin's prints differently.", source: "BBC Science Focus" },
  { id: 3, text: "Earth's spin is gradually slowing down, adding about 1.8 seconds to the length of a day every century.", source: "BBC Science Focus" },
  { id: 4, text: "Cooling cooked pasta converts some of its starch into a resistant starch that's easier on blood sugar.", source: "BBC Science Focus" },
  { id: 5, text: "Surveys in the US find that parents report lower overall happiness than people without kids.", source: "BBC Science Focus" },
  { id: 6, text: "A thunderstorm nicknamed 'Hector the Convector' forms over Australia's Tiwi Islands almost every afternoon around 3pm.", source: "BBC Science Focus" },
  { id: 7, text: "Earlobes are packed with nerve endings but scientists still aren't sure they serve any biological purpose.", source: "BBC Science Focus" },
  { id: 8, text: "When you read silently, your mouth, tongue, and throat muscles still twitch slightly as your brain 'sounds out' the words.", source: "BBC Science Focus" },
  { id: 9, text: "The largest fossilized dinosaur dropping ever found, likely from a T. rex, was over 30cm long and held about two liters.", source: "BBC Science Focus" },
  { id: 10, text: "Mars isn't a perfect sphere — its odd internal structure makes it slightly rugby-ball-shaped compared to other rocky planets.", source: "BBC Science Focus" },
  { id: 11, text: "There's no such thing as a truly zero-calorie food — even digesting celery costs your body a small amount of energy.", source: "BBC Science Focus" },
  { id: 12, text: "Around 8-10% of people grind their teeth in their sleep without ever realizing it.", source: "BBC Science Focus" },
  { id: 13, text: "Astronomers once averaged the color of every star in the universe and got a shade of beige they nicknamed 'cosmic latte.'", source: "BBC Science Focus" },
  { id: 14, text: "Water isn't technically 'wet' — wetness describes how a liquid clings to a solid surface, not a property of the water itself.", source: "BBC Science Focus" },
  { id: 15, text: "Cats mostly tolerate petting in exchange for food or attention, and tend to prefer being stroked on the chin and cheeks over the back.", source: "BBC Science Focus" },
  { id: 16, text: "Newborn babies see the world in a narrow range of colors because the cone cells in their eyes aren't fully developed yet.", source: "BBC Science Focus" },
  { id: 17, text: "The raw chemical elements that make up a human body would cost over £116,000 if bought individually in refined form.", source: "BBC Science Focus" },
  { id: 18, text: "If you stacked up every bacterium on Earth end to end, the line would stretch about 10 billion light-years.", source: "BBC Science Focus" },
  { id: 19, text: "Wearing a necktie can measurably reduce blood flow to the brain, sometimes enough to cause light dizziness.", source: "BBC Science Focus" },
  { id: 20, text: "Hippopotomonstrosesquippedaliophobia — the fear of long words — is itself 36 letters long.", source: "BBC Science Focus" },
  { id: 21, text: "The oldest dog on record, an Australian cattle dog named Bluey, lived to 29 and a half years old.", source: "BBC Science Focus" },
  { id: 22, text: "The oldest cat on record, Creme Puff, lived to 38 years and three days old.", source: "BBC Science Focus" },
  { id: 23, text: "Humans have physically explored less than 0.001% of the ocean floor.", source: "BBC Science Focus" },
  { id: 24, text: "Measured from base to peak, Hawaii's Mauna Kea is taller than Mount Everest — most of it just happens to be underwater.", source: "BBC Science Focus" },
  { id: 25, text: "The heliopause — where the Sun's solar wind finally fades against interstellar space — marks the outer edge of the solar system.", source: "BBC Science Focus" },
  { id: 26, text: "The Mercator map projection, still used everywhere, dramatically distorts the true size of continents near the poles.", source: "BBC Science Focus" },
  { id: 27, text: "The Moon drifts away from Earth by about 3cm every year.", source: "BBC Science Focus" },
  { id: 28, text: "Comets contain compounds like hydrogen sulfide and ammonia, giving them a genuinely foul, rotten-egg-like smell.", source: "BBC Science Focus" },
  { id: 29, text: "Earth's magnetic poles have flipped 171 times over the last 71 million years.", source: "BBC Science Focus" },
  { id: 30, text: "Intensely prolonged laughter has, in rare documented cases, triggered fatal heart attacks or suffocation.", source: "BBC Science Focus" },
  { id: 31, text: "The chainsaw was originally invented in the late 1700s as a surgical tool for childbirth.", source: "BBC Science Focus" },
  { id: 32, text: "Cats often prefer sleeping on their left side, possibly because it keeps their right hemisphere — tied to threat response — more alert.", source: "BBC Science Focus" },
  { id: 33, text: "You lose heat evenly across your whole body — the idea that your head loses the most is a myth.", source: "BBC Science Focus" },
  { id: 34, text: "Fossil evidence suggests T. rex was likely covered in feathers, at least early in its life.", source: "BBC Science Focus" },
  { id: 35, text: "Football teams that wear red kits statistically win more often at home than teams in other colors.", source: "BBC Science Focus" },
  { id: 36, text: "A cut earthworm can regrow its tail, and some flatworms can regenerate an entire new body from a single fragment.", source: "BBC Science Focus" },
  { id: 37, text: "UK wind turbines are estimated to kill tens of thousands of birds a year, but painting just one blade black cuts that by around 70%.", source: "BBC Science Focus" },
  { id: 38, text: "Regularly playing board games like Monopoly has been linked to better long-term cognitive function and lower dementia risk.", source: "BBC Science Focus" },
  { id: 39, text: "Microsoft's anechoic testing chamber in Washington measures -20.6 decibels, making it the quietest man-made place on record.", source: "BBC Science Focus" },
  { id: 40, text: "A horse can briefly produce around 24 horsepower — well beyond the single unit named after it.", source: "BBC Science Focus" },
  { id: 41, text: "About 60% of the human body is water, which is part of why your weight fluctuates slightly throughout the day.", source: "BBC Science Focus" },
  { id: 42, text: "In 1912, inventor Franz Reichelt died testing a wearable parachute suit by jumping from the Eiffel Tower.", source: "BBC Science Focus" },
  { id: 43, text: "Orcas have been observed wearing dead salmon on their heads like hats, for reasons scientists still can't fully explain.", source: "BBC Science Focus" },
  { id: 44, text: "Some deaf people who use sign language have been observed signing in their sleep during REM behavior disorder episodes.", source: "BBC Science Focus" },
  { id: 45, text: "There are several documented cases in Indonesia of large pythons swallowing an adult human whole.", source: "BBC Science Focus" },
  { id: 46, text: "Finland has topped the World Happiness Report as the world's happiest country for six years running.", source: "BBC Science Focus" },
  { id: 47, text: "Hippos can't actually swim. Their dense bones sink, so they move by galloping along the riverbed.", source: "BBC Science Focus" },
  { id: 48, text: "In the Southern Hemisphere the Moon appears upside-down compared to the north, and its markings look more like a rabbit.", source: "BBC Science Focus" },
  { id: 49, text: "An astronaut aboard the ISS once successfully played with a yo-yo in microgravity.", source: "BBC Science Focus" },
  { id: 50, text: "Some sea slugs steal chlorophyll from the algae they eat and use it to photosynthesize like a plant.", source: "BBC Science Focus" },
  { id: 51, text: "About 1 in 500 pregnancies go unnoticed until halfway through, and roughly 1 in 2,500 aren't discovered until labor begins.", source: "BBC Science Focus" },
  { id: 52, text: "A common skin bacterium, Staphylococcus aureus, can directly trigger the nerve pathways that make you feel itchy.", source: "BBC Science Focus" },
  { id: 53, text: "Polar bears have black skin underneath their white fur.", source: "BBC Science Focus" },
  { id: 54, text: "A starfish doesn't really have a body — biologically, it's classified as almost entirely head.", source: "BBC Science Focus" },
  { id: 55, text: "In 2013, doctors in India surgically removed a football-sized mass of impacted feces from a woman's body.", source: "BBC Science Focus" },
  { id: 56, text: "Earth travels roughly 2.5 million kilometers through space every single day just orbiting the Sun.", source: "BBC Science Focus" },
  { id: 57, text: "Neon tetra fish form orderly single-file queues when squeezing through narrow gaps to escape danger.", source: "BBC Science Focus" },
  { id: 58, text: "By cell count, humans are roughly 56% bacteria — though those microbes are so small they make up under 1% of our body weight.", source: "BBC Science Focus" },
  { id: 59, text: "Roughly three-quarters of ginger cats are male, a quirk of how the coloring gene sits on the X chromosome.", source: "BBC Science Focus" },
  { id: 60, text: "Fingernails grow faster in hot summer months, likely due to increased blood flow to the fingertips.", source: "BBC Science Focus" },
  { id: 61, text: "Statistically, the Bermuda Triangle sees no more shipwrecks or disappearances than any other similarly busy stretch of ocean.", source: "BBC Science Focus" },
  { id: 62, text: "Alpine bumblebees have been recorded flying at 3.25km altitude, and lab tests suggest they could physically manage twice that.", source: "BBC Science Focus" },
  { id: 63, text: "The exoplanet 55 Cancri e, twice Earth's size, is thought to be made largely of carbon — possibly including actual diamond.", source: "BBC Science Focus" },
  { id: 64, text: "Male anglerfish permanently fuse to females during mating, eventually shrinking into little more than a living sperm-producing sac.", source: "BBC Science Focus" },
  { id: 65, text: "A rare condition called auto-brewery syndrome lets gut bacteria ferment carbs into ethanol, making people intoxicated without drinking alcohol.", source: "BBC Science Focus" },
  { id: 66, text: "Researchers have experimented with synchronizing lucid dreamers' brains to let them exchange simple messages mid-dream.", source: "BBC Science Focus" },
  { id: 67, text: "Quicksand is too dense to fully swallow a person — leaning back and moving slowly lets you float free.", source: "BBC Science Focus" },
  { id: 68, text: "Emperor penguins typically dive 100-200 meters for food, but the deepest recorded dive reached about 550 meters.", source: "BBC Science Focus" },
  { id: 69, text: "Pets can develop allergies to human dead skin cells (dander), much like humans can be allergic to theirs.", source: "BBC Science Focus" },
  { id: 70, text: "Boredom isn't a low-energy state — it's actually linked to a physiological arousal spike, including a faster heart rate.", source: "BBC Science Focus" },
  { id: 71, text: "Your immune system distinguishes harmful bacteria from helpful ones largely by recognizing specific molecular patterns on their surface.", source: "BBC Science Focus" },
  { id: 72, text: "A platypus has no teats — it feeds its young milk that seeps out through its skin like sweat.", source: "BBC Science Focus" },
  { id: 73, text: "A single LEGO brick can support the weight of about 375,000 other bricks stacked on top of it.", source: "BBC Science Focus" },
  { id: 74, text: "Studies of combat sports have found that athletes who smile before a match are statistically more likely to lose it.", source: "BBC Science Focus" },
  { id: 75, text: "Whole fresh fruit is hard to overeat for sugar, since its fiber and water content help trigger fullness before that happens.", source: "BBC Science Focus" },
  { id: 76, text: "Your own voice sounds different to you than to others because you hear part of it through bone conduction, which emphasizes lower tones.", source: "BBC Science Focus" },
  { id: 77, text: "The ring-shaped rainbows called 'glories' seen in Venus's clouds come from light-wave interference, not standard refraction like a normal rainbow.", source: "BBC Science Focus" },
  { id: 78, text: "Depending on how fast their inner quarks move, protons can appear shaped like anything from a peanut to a rugby ball to a sphere.", source: "BBC Science Focus" },
  { id: 79, text: "Two mirrors facing each other only produce a few hundred reflections before the image fades out, since each bounce absorbs some light.", source: "BBC Science Focus" },
  { id: 80, text: "Cognitive behavioral therapy and structured training programs have been shown to reduce psychopathic traits and boost empathy in some individuals.", source: "BBC Science Focus" },
  { id: 81, text: "Goosebumps happen in essentially all mammals, not just humans — it's a shared reflex from tiny muscles at the base of each hair.", source: "BBC Science Focus" },
  { id: 82, text: "Intense exercise increases protein levels in saliva, making it thicker and harder to swallow — which is why athletes spit more.", source: "BBC Science Focus" },
  { id: 83, text: "Some animals display autism-like traits, including repetitive behaviors and atypical social interaction patterns.", source: "BBC Science Focus" },
  { id: 84, text: "The Queen Alexandra's Birdwing, found in Papua New Guinea, is the world's largest butterfly with a wingspan up to 31cm.", source: "BBC Science Focus" },
  { id: 85, text: "Waking up frequently during the night and having generally poor sleep quality actually makes you more likely to remember your dreams.", source: "BBC Science Focus" },
  { id: 86, text: "Sweat produced during anxiety carries a distinct chemical signal that other people's brains can subconsciously detect as a warning.", source: "BBC Science Focus" },
  { id: 87, text: "A lightning bolt can reach around 30,000°C — roughly five times hotter than the surface of the Sun.", source: "BBC Science Focus" },
  { id: 88, text: "The record for holding your breath underwater is 24 minutes and 37 seconds, set by Croatian freediver Budimir Šobat.", source: "BBC Science Focus" },
  { id: 89, text: "The Moon is slowly shrinking, losing around 50 meters of radius every few hundred million years as its interior cools.", source: "BBC Science Focus" },
  { id: 90, text: "Dogs tilt their heads partly to better locate the source of a sound and to recognize familiar words more accurately.", source: "BBC Science Focus" },
  { id: 91, text: "If Earth's diameter doubled while keeping the same density, surface gravity would double too — likely snapping trees and shattering bones.", source: "BBC Science Focus" },
  { id: 92, text: "Despite Venus being called Earth's 'twin,' Mercury is actually the closer planet to Earth on average.", source: "BBC Science Focus" },
  { id: 93, text: "Flamingos are born gray and white; their pink color comes later, from pigments in the shrimp and algae they eat.", source: "BBC Science Focus" },
  { id: 94, text: "Threatened ants release distinct warning chemicals, and some species — like trap-jaw ants — reportedly smell like chocolate when agitated.", source: "BBC Science Focus" },
  { id: 95, text: "Naturally thin people often have slower resting metabolisms, partly because they tend to carry less metabolically active muscle mass.", source: "BBC Science Focus" },
  { id: 96, text: "Entomologist Justin Schmidt famously let himself be stung by dozens of insect species to build a scientific ranking of sting pain.", source: "BBC Science Focus" },
  { id: 97, text: "Radiometric dating puts Earth's age at approximately 4.54 billion years old.", source: "BBC Science Focus" },
  { id: 98, text: "Contrary to popular belief, moderate alcohol poses minimal risk with most common antibiotics — though it's still worth checking specific drugs.", source: "BBC Science Focus" },
  { id: 99, text: "Physicists estimate an electron's minimum possible lifetime at a staggering 6.6 × 10^28 years.", source: "BBC Science Focus" },
  { id: 100, text: "Beavers don't actually live inside their dams — they build separate lodges nearby, using the dam mainly to raise water levels.", source: "BBC Science Focus" },
  { id: 101, text: "T. rex reached full adult size by around 16-22 years old and typically lived to about 27-33.", source: "BBC Science Focus" },
  { id: 102, text: "Apollo 16 astronaut Charles Duke left a photograph of his family on the Moon's surface in 1972.", source: "BBC Science Focus" },
  { id: 103, text: "Saturn's moon Titan has methane rain and rivers — the only other place in the solar system known to have liquid on its surface.", source: "BBC Science Focus" },
  { id: 104, text: "Giraffes communicate with each other using low-frequency humming sounds, especially at night when the herd gets separated.", source: "BBC Science Focus" },
  { id: 105, text: "Some glass sponges are estimated to live up to 15,000 years, making them among the longest-lived organisms on Earth.", source: "BBC Science Focus" },
  { id: 106, text: "In any group of just 23 people, there's better than even odds — about 50.7% — that two of them share a birthday.", source: "BBC Science Focus" },
  { id: 107, text: "Murder rates in the US rise by roughly 2.7% during summer months compared to the rest of the year.", source: "BBC Science Focus" },
  { id: 108, text: "That 'new car smell' is actually a cocktail of over 200 chemicals off-gassing from plastics and adhesives, including some toxic compounds like benzene.", source: "BBC Science Focus" },
  { id: 109, text: "Sea level is naturally higher at the equator than near the poles, thanks to the centrifugal effect of Earth's rotation.", source: "BBC Science Focus" },
  { id: 110, text: "You inhale roughly 50 potentially harmful bacteria with every single breath you take.", source: "BBC Science Focus" },
  { id: 111, text: "Some stars visible to the naked eye are so far away that their light left them up to 4,000 years ago.", source: "BBC Science Focus" },
  { id: 112, text: "The earliest land plants reproduced with spores, like moss does today — seeds didn't evolve until roughly 150 million years later.", source: "BBC Science Focus" },
  { id: 113, text: "Dead cells in your body are cleaned up by phagocytes, a type of white blood cell that essentially eats cellular debris.", source: "BBC Science Focus" },
  { id: 114, text: "Odor molecules can travel and be detected through liquid, not just air.", source: "BBC Science Focus" },
  { id: 115, text: "Despite the 'blind as a bat' saying, bats can see fine — they just rely on echolocation as their primary hunting sense.", source: "BBC Science Focus" },
  { id: 116, text: "Most hibernating animals don't dream because their brain activity drops too low, though fat-tailed lemurs appear to be an exception.", source: "BBC Science Focus" },
  { id: 117, text: "Pine cones close up when humidity rises, which folk wisdom has long used as a rough sign that rain is coming.", source: "BBC Science Focus" },
  { id: 118, text: "A standard sheet of paper can't be folded in half more than about 8 times by hand — the world record, using a giant sheet, is 12.", source: "BBC Science Focus" },
  { id: 119, text: "The sharpest teeth ever measured belonged to conodonts, extinct eel-like creatures, with tips just two micrometers wide.", source: "BBC Science Focus" },
  { id: 120, text: "Laughter likely predates human language entirely — even baby apes show ticklish laughter responses similar to ours.", source: "BBC Science Focus" },
  { id: 121, text: "NASA's experimental X-43 aircraft reached nearly 11,854 km/h — close to ten times the speed of sound.", source: "BBC Science Focus" },
  { id: 122, text: "South Korea has some of the lowest average 'bad' cholesterol levels in the world, credited partly to a diet rich in fermented foods.", source: "BBC Science Focus" },
  { id: 123, text: "Some companies have experimented with technology aimed at letting lucid dreamers exchange messages with each other mid-dream.", source: "BBC Science Focus" },
  { id: 124, text: "Cats often sit on your laptop or keyboard partly to overwrite your scent with theirs, marking it as their territory.", source: "BBC Science Focus" },
  { id: 125, text: "Medieval bearded vultures in Spain reportedly built nests incorporating old sandals and even crossbow parts.", source: "BBC Science Focus" },
  { id: 126, text: "Scientists only formally identified the interstitium — a fluid-filled tissue network some call the body's largest organ — within the last decade.", source: "BBC Science Focus" },
  { id: 127, text: "Many reptiles excrete solid or paste-like urine instead of liquid, an adaptation that helps them conserve water.", source: "BBC Science Focus" },
  { id: 128, text: "Studies have found men's handwriting tends to be rated worse than women's, who also tend to write somewhat faster.", source: "BBC Science Focus" },
  { id: 129, text: "Trying hard to stop a dog from eating feces can sometimes backfire, making the dog fixate on it more.", source: "BBC Science Focus" },
  { id: 130, text: "A roughly 1,200 km² area of France, the 'Zone Rouge,' remains off-limits over a century later due to unexploded WWI ordnance.", source: "BBC Science Focus" },
  { id: 131, text: "Medieval war horses were often pony-sized by modern standards, making it easier for armored knights to remount after falling.", source: "BBC Science Focus" },
  { id: 132, text: "Semen from an elite breeding bull can sell for tens of thousands of pounds per milliliter.", source: "BBC Science Focus" },
  { id: 133, text: "Pompeii worms live near hydrothermal vents and can tolerate near-boiling water, among the most heat-tolerant animals known.", source: "BBC Science Focus" },
  { id: 134, text: "'Skyquakes' — mysterious booming sounds from the sky with no confirmed source — have been reported for centuries and remain unexplained.", source: "BBC Science Focus" },
  { id: 135, text: "At the atomic level you never truly touch anything — what you feel as contact is electromagnetic repulsion between electrons.", source: "BBC Science Focus" },
  { id: 136, text: "A sweet, acetone-like body odor can sometimes be an early warning sign of diabetes or other metabolic conditions.", source: "BBC Science Focus" },
  { id: 137, text: "One study estimated the average time to fully emotionally recover from a serious breakup at around 4.18 years.", source: "BBC Science Focus" },
  { id: 138, text: "People today walk roughly 15% faster on average than people did in 1980, and researchers aren't entirely sure why.", source: "BBC Science Focus" },
  { id: 139, text: "Physicists have successfully used powerful magnets to levitate a live frog, demonstrating diamagnetic levitation.", source: "BBC Science Focus" },
  { id: 140, text: "There are documented medical cases of people surviving extended periods without a functioning heart, and others surviving major brain tissue loss.", source: "BBC Science Focus" },
  { id: 141, text: "Whale urine helps redistribute vital nutrients across ocean basins, an effect researchers call the 'great whale conveyor belt.'", source: "BBC Science Focus" },
  { id: 142, text: "Studies estimate that somewhere between 1% and 7% of children are unknowingly raised by a father who isn't their biological one.", source: "BBC Science Focus" },
  { id: 143, text: "Snakes can't digest hair, nails, or fabric — these pass through undigested if a snake happens to swallow them with its prey.", source: "BBC Science Focus" },
  { id: 144, text: "Horseshoe crabs have blue, copper-based blood, and a compound in it is used to test medical equipment for bacterial contamination.", source: "BBC Science Focus" },
  { id: 145, text: "Over an average 80-year life, you'll spend roughly 3.5 years of it with your eyes closed just from blinking.", source: "BBC Science Focus" },
  { id: 146, text: "Stone circles in Australia, dated to around 10,000 years old, predate Stonehenge by thousands of years.", source: "BBC Science Focus" },
  { id: 147, text: "Museum researchers describe the smell of ancient Egyptian mummies as woody, spicy, and faintly sweet.", source: "BBC Science Focus" },
  { id: 148, text: "An hour of walking burns roughly 250 calories for an average person, more on an incline.", source: "BBC Science Focus" },
  { id: 149, text: "It's physically impossible to swallow your own tongue — a persistent myth that has led to harmful, unnecessary first-aid attempts.", source: "BBC Science Focus" },
  { id: 150, text: "Golden jewel beetles can live for decades, reportedly into their 40s — extraordinarily long for an insect.", source: "BBC Science Focus" },
  { id: 151, text: "The Challenger Deep in the Mariana Trench plunges over 10,900 meters down, the deepest known point in Earth's oceans.", source: "BBC Science Focus" }
];
